FROM    hirokimatsumoto/alpine-openjdk-11:latest as alpha
RUN     apk upgrade --available
RUN     apk add --no-cache ca-certificates java-cacerts openssl binutils
RUN     jlink \
        --module-path /opt/java/jmods \
        --compress=2 \
        --add-modules "jdk.management.agent,java.base,java.logging,java.xml,jdk.unsupported,java.sql,java.naming,java.desktop,java.management,java.security.jgss,java.instrument,java.scripting,jdk.crypto.ec,java.rmi,jdk.httpserver,jdk.zipfs,jdk.net" \
        --strip-debug \
        --no-header-files \
        --no-man-pages \
        --ignore-signing-information \
        --output /lib/runtime \
        && rm -rf /lib/apk \
        && rm -rf /lib/runtime/legal \
        && rm -rf /lib/runtime/security \
        && strip --strip-unneeded /lib/runtime/lib/server/libjvm.so \
        && cd /lib/runtime/lib;for i in `ls /lib/runtime/lib | grep -i so | awk '{ print $1}'`; do strip --strip-unneeded $i;done

FROM scratch
COPY --chown=1001:1001 --from=alpha /lib /lib
COPY --chown=1001:1001 --from=alpha /tmp /tmp
ADD --chown=1001:1001 a /opt/commonvolume/
EXPOSE 8080
USER 1001
ENTRYPOINT ["/lib/runtime/bin/java",  "-jar", "/opt/app/app.jar"]