apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hellocloud-app
  name: hellocloud-app
  namespace: hellocloud-ns
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hellocloud-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hellocloud-app
