---
#apiVersion: "v1"
#kind: "Namespace"
#metadata:
#  name: "hellocloud-ns"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hellocloud-app"
  namespace: "hellocloud"
  labels:
    app: "hellocloud-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "hellocloud-app"
  template:
    metadata:
      labels:
        app: "hellocloud-app"
    spec:
      containers:
      - name: "hellocloud"
        image: "devopscloud987/hellocloud:latest"
